In [1]:
import numpy as np
I = np.eye(3)
print("Identity:\n",I)

A = np.array([[2,3],[1,3]])
A_inv = np.linalg.inv(A)
print("A invese:\n",A_inv)
print("A @ A_invese:\n",A @ A_inv)


Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A invese:
 [[ 1.         -1.        ]
 [-0.33333333  0.66666667]]
A @ A_invese:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 5.55111512e-17  1.00000000e+00]]
