1. Matrix Creation & Basic Operations

In [1]:
import numpy as np

A = np.array([[2, 1],
              [0, 3]])

B = np.array([[1, 4],
              [2, 5]])

print("A + B =\n", A + B)

print("\nA transpose =\n", A.T)

print("\nA @ B =\n", A @ B)   # Matrix multiplication

A + B =
 [[3 5]
 [2 8]]

A transpose =
 [[2 0]
 [1 3]]

A @ B =
 [[ 4 13]
 [ 6 15]]


2. Identity Matrix & Matrix Inverse

In [2]:
import numpy as np

I = np.eye(3)

print("Identity Matrix:\n", I)

A = np.array([[2, 1],
              [1, 3]])

A_inv = np.linalg.inv(A)

print("\nA inverse:\n", A_inv)

print("\nA @ A_inv =\n", A @ A_inv)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

A @ A_inv =
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


3. Solving Ax = b

In [3]:
import numpy as np

# Solve:
# 2x + y = 5
# x + 3y = 7

A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 7])

x = np.linalg.solve(A, b)

print("Solution:", x)

# Verification
print("Check:", A @ x)

Solution: [1.6 1.8]
Check: [5. 7.]


Exercise Solution (3×3 Real-World Scenario)
Product Pricing Problem

Suppose a shop sells:

Product A
Product B
Product C

Customer Orders:

Order	Product A	Product B	Product C	Total Bill
1	2	1	1	₹130
2	1	3	2	₹230
3	3	2	4	₹310

Find the price of each product

In [4]:
import numpy as np

A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [3, 2, 4]
])

b = np.array([
    130,
    230,
    310
])

prices = np.linalg.solve(A, b)

print("Product Prices:")
print("Product A =", prices[0])
print("Product B =", prices[1])
print("Product C =", prices[2])

# Verification
print("\nVerification:")
print(A @ prices)

Product Prices:
Product A = 24.545454545454536
Product B = 43.63636363636363
Product C = 37.27272727272728

Verification:
[130. 230. 310.]
